<?php if ($this->pageCount): ?>
     <nav aria-label="Page navigation example">
         <ul class="pagination">
             <?php if (isset($this->previous)): ?>
                 <li class="page-item">
                     <a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>
                     <?php ($this->get_params!='') ? $tmp = '&'.$this->get_params : $tmp = '';
                     echo $tmp?>">
                         Назад
                     </a>
                 </li>
             <?php else: ?>
                 <li class="page-item disabled">
                     <a class="page-link" href="#" tabindex="-1">
                         Назад
                     </a>
                 </li>
             <?php endif; ?>

             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li class="page-item">
                         <a class="page-link" href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?><?php ($this->get_params!='') ? $tmp = '&'.$this->get_params : $tmp = '';
                     echo $tmp?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="page-item active">
                         <a class="page-link" href="#"><?php echo $page; ?><span class="sr-only">(current)</span></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <?php if (isset($this->next)): ?>
                 <li class="page-item">
                     <a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?><?php ($this->get_params!='') ? $tmp = '&'.$this->get_params : $tmp = '';
                     echo $tmp?>">
                         Вперед
                     </a>
                 </li>
             <?php else: ?>
                 <li class="page-item disabled">
                     <a class="page-link" href="#" tabindex="-1">
                         Вперед
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </nav>
 <?php endif; ?>